# Generated by Django 4.2.16 on 2025-08-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('provider', 'Provider')], default='seeker', max_length=20, verbose_name='role'),
        ),
    ]
