# Generated by Django 4.2.16 on 2025-08-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0003_application_employer_customuser_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
